[package]
name = "OnChainRadio"
version = "1.0.0"
authors = []

[addresses]
radio_addrx = '5e8cecb3b39d82b6f41519e5012e62837d816f2f0006d021742e246528a8ffaa'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
